
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: arrow_r
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Threshold Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>
#include "tImage.h"


static const uint8_t image_data_arrow_r[11] = {
    // ∙█████
    // ∙∙████
    // ∙∙∙███
    // ∙∙∙∙██
    // ∙∙∙∙∙█
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙█
    // ∙∙∙∙██
    // ∙∙∙███
    // ∙∙████
    // ∙█████
    0x7c, 
    0x3c, 
    0x1c, 
    0x0c, 
    0x04, 
    0x00, 
    0x04, 
    0x0c, 
    0x1c, 
    0x3c, 
    0x7c
};
const tImage arrow_r = { image_data_arrow_r, 6, 11,
    8 };

