
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: battery_chrg
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>
#include "tImage.h"


static const uint8_t image_data_battery_chrg[90] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██
    // ∙∙███████████████████████████∙∙██
    // ∙∙████████████∙██████████████∙∙██
    // ∙∙████████████∙∙█████████████∙∙██
    // ∙∙████████████∙∙∙████████████∙∙██
    // ∙∙████████████∙∙∙∙∙██████████∙∙∙∙
    // ∙∙████∙∙∙∙∙∙∙∙∙∙∙∙∙∙█████████∙∙∙∙
    // ∙∙█████∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙███████∙∙∙∙
    // ∙∙██████∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█████∙∙∙∙
    // ∙∙████████∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙∙∙∙
    // ∙∙██████████∙∙∙∙∙████████████∙∙∙∙
    // ∙∙████████████∙∙∙████████████∙∙██
    // ∙∙█████████████∙∙████████████∙∙██
    // ∙∙██████████████∙████████████∙∙██
    // ∙∙███████████████████████████∙∙██
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██
    0x00, 0x00, 0x00, 0x01, 0x80, 
    0x00, 0x00, 0x00, 0x01, 0x80, 
    0x3f, 0xff, 0xff, 0xf9, 0x80, 
    0x3f, 0xfd, 0xff, 0xf9, 0x80, 
    0x3f, 0xfc, 0xff, 0xf9, 0x80, 
    0x3f, 0xfc, 0x7f, 0xf9, 0x80, 
    0x3f, 0xfc, 0x1f, 0xf8, 0x00, 
    0x3c, 0x00, 0x0f, 0xf8, 0x00, 
    0x3e, 0x00, 0x03, 0xf8, 0x00, 
    0x3f, 0x00, 0x00, 0xf8, 0x00, 
    0x3f, 0xc0, 0x00, 0x78, 0x00, 
    0x3f, 0xf0, 0x7f, 0xf8, 0x00, 
    0x3f, 0xfc, 0x7f, 0xf9, 0x80, 
    0x3f, 0xfe, 0x7f, 0xf9, 0x80, 
    0x3f, 0xff, 0x7f, 0xf9, 0x80, 
    0x3f, 0xff, 0xff, 0xf9, 0x80, 
    0x00, 0x00, 0x00, 0x01, 0x80, 
    0x00, 0x00, 0x00, 0x01, 0x80
};
const tImage battery_chrg = { image_data_battery_chrg, 33, 18,
    8 };

