
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: usb_logo
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>
#include "tImage.h"


static const uint8_t image_data_usb_logo[76] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙███████∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙██∙∙████∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙██∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙██∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙∙∙
    // ∙████∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙
    // ██████∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙███∙∙∙
    // ███████████████████████████∙∙
    // ████████████████████████████∙
    // ██████∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙████∙∙
    // ∙████∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙███∙∙∙
    // ∙∙██∙∙∙∙∙∙∙∙∙█∙∙∙∙∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙████∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0xc0, 0x00, 
    0x00, 0x01, 0xe0, 0x00, 
    0x00, 0x0f, 0xe0, 0x00, 
    0x00, 0x19, 0xe0, 0x00, 
    0x00, 0x30, 0xc0, 0x00, 
    0x30, 0x60, 0x01, 0x00, 
    0x78, 0xc0, 0x01, 0x80, 
    0xfc, 0xc0, 0x01, 0xc0, 
    0xff, 0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xff, 0xf0, 
    0xfc, 0x18, 0x01, 0xe0, 
    0x78, 0x0c, 0x01, 0xc0, 
    0x30, 0x04, 0x01, 0x80, 
    0x00, 0x06, 0x79, 0x00, 
    0x00, 0x03, 0x78, 0x00, 
    0x00, 0x01, 0xf8, 0x00, 
    0x00, 0x00, 0x78, 0x00, 
    0x00, 0x00, 0x78, 0x00
};
const tImage usb_logo = { image_data_usb_logo, 29, 19,
    8 };

