
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: user_logo
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>
#include "tImage.h"



static const uint8_t image_data_user_logo[57] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙████∙∙∙∙∙∙∙
    // ∙∙∙∙∙██████∙∙∙∙∙∙
    // ∙∙∙∙████████∙∙∙∙∙
    // ∙∙∙██████████∙∙∙∙
    // ∙∙∙██████████∙∙∙∙
    // ∙∙∙██████████∙∙∙∙
    // ∙∙∙∙████████∙∙∙∙∙
    // ∙∙∙∙∙██████∙∙∙∙∙∙
    // ∙∙█∙∙∙████∙∙∙█∙∙∙
    // ∙∙███∙∙∙∙∙∙████∙∙
    // ∙███████████████∙
    // ∙███████████████∙
    // █████████████████
    // █████████████████
    // █████████████████
    // █████████████████
    // ∙███████████████∙
    // ∙∙∙███████████∙∙∙
    0x00, 0x00, 0x00, 
    0x03, 0xc0, 0x00, 
    0x07, 0xe0, 0x00, 
    0x0f, 0xf0, 0x00, 
    0x1f, 0xf8, 0x00, 
    0x1f, 0xf8, 0x00, 
    0x1f, 0xf8, 0x00, 
    0x0f, 0xf0, 0x00, 
    0x07, 0xe0, 0x00, 
    0x23, 0xc4, 0x00, 
    0x38, 0x1e, 0x00, 
    0x7f, 0xff, 0x00, 
    0x7f, 0xff, 0x00, 
    0xff, 0xff, 0x80, 
    0xff, 0xff, 0x80, 
    0xff, 0xff, 0x80, 
    0xff, 0xff, 0x80, 
    0x7f, 0xff, 0x00, 
    0x1f, 0xfc, 0x00
};
const tImage user_logo = { image_data_user_logo, 17, 19,
    8 };

