
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: antenna
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>
#include "tImage.h"


static const uint8_t image_data_antenna[54] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙█████∙∙∙█████∙∙∙
    // █∙∙∙████∙∙∙████∙∙∙█
    // ██∙∙∙███∙∙∙███∙∙∙██
    // ███∙∙∙██∙∙∙██∙∙∙███
    // ████∙∙∙█∙∙∙█∙∙∙████
    // █████∙∙∙∙∙∙∙∙∙█████
    // ██████∙∙∙∙∙∙∙██████
    // ███████∙∙∙∙∙███████
    // ████████∙∙∙████████
    // ████████∙∙∙████████
    // ████████∙∙∙████████
    // ████████∙∙∙████████
    // ████████∙∙∙████████
    // ████████∙∙∙████████
    // ████████∙∙∙████████
    // ████████∙∙∙████████
    0x00, 0x00, 0x00, 
    0x00, 0x00, 0x00, 
    0x1f, 0x1f, 0x00, 
    0x8f, 0x1e, 0x20, 
    0xc7, 0x1c, 0x60, 
    0xe3, 0x18, 0xe0, 
    0xf1, 0x11, 0xe0, 
    0xf8, 0x03, 0xe0, 
    0xfc, 0x07, 0xe0, 
    0xfe, 0x0f, 0xe0, 
    0xff, 0x1f, 0xe0, 
    0xff, 0x1f, 0xe0, 
    0xff, 0x1f, 0xe0, 
    0xff, 0x1f, 0xe0, 
    0xff, 0x1f, 0xe0, 
    0xff, 0x1f, 0xe0, 
    0xff, 0x1f, 0xe0, 
    0xff, 0x1f, 0xe0
};
const tImage antenna = { image_data_antenna, 19, 18,
    8 };

