
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: arrow_d
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Threshold Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>
#include "tImage.h"


static const uint8_t image_data_arrow_d[12] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙∙∙█
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ████∙∙∙████
    // █████∙█████
    0x00, 0x00, 
    0x80, 0x20, 
    0xc0, 0x60, 
    0xe0, 0xe0, 
    0xf1, 0xe0, 
    0xfb, 0xe0
};
const tImage arrow_d = { image_data_arrow_d, 11, 6,
    8 };

